### ISSUE TITLE
error when comparing datetimes

### ISSUE THREAD

**Issue by avoine** [radiac/django-yarr#43]
After adding: https://news.ycombinator.com/rss I got this error:

<pre>
python manage.py check_feeds
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/srv/src/django-yarr/yarr/decorators.py", line 19, in wrap
    r = fn(*args, **kwargs)
  File "/srv/src/django-yarr/yarr/management/commands/check_feeds.py", line 79, in handle
    logfile=self.stdout if options['verbose'] else None,
  File "/srv/src/django-yarr/yarr/managers.py", line 26, in check
    feed.check(force, read, logfile)
  File "/srv/src/django-yarr/yarr/models.py", line 274, in check
    changed = self._do_check(force, read, logfile)
  File "/srv/src/django-yarr/yarr/models.py", line 301, in _do_check
    and self.next_check >= next_poll
TypeError: can't compare offset-naive and offset-aware datetimes
</pre>

**Comment by fspegni** [comment]
any news on this? I'm still seeing this bug, has it been addressed somehow? Thanks
